### ISSUE TITLE
Fix gdal imports

### ISSUE THREAD

**Issue by rhugonnet** [iamdonovan/pyddem#2]
_Following a comment from Maud Bernat_:

We need to fix the imports with the latest version of gdal (actually I think I had to it also fairly recently).
All the:
```python
import gdal, osr, ogr, gdalconst
```
Need to be changed into:
```python
from osgeo import gdal, osr, ogr, gdalconst
```
@iamdonovan did you have do this in your `dev` branch, recently updated, maybe? If yes we could potentially merge that with main.

**Comment by iamdonovan** [comment]
resolved with #4
